#!/bin/sh
# SPDX-License-Identifier: GPL-3.0-or-later
# copyright 2025 mannikim <mannikim[at]proton[dot]me>
# this file is part of pie
# see LICENSE file for the license text
dmenu -p "New color (4 byte hex)" <<EOF
EOF
