#!/bin/sh
# SPDX-License-Identifier: GPL-3.0-or-later
# copyright 2025-2026 mannikim <mannikim[at]proton[dot]me>
# this file is part of pie
# see LICENSE file for the license text
ans="$(pcp)"
if [ ! -z "$?" ]; then
	echo "setcolor $ans" > /tmp/pie.fifo
fi
